version: '3'
services:
 api:
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgresql://kellcrivelaro92:kiCx8ZdQ6mPa@ep-small-credit-418178.us-west-2.aws.neon.tech/loterias?sslmode=require
      - API_URL=https://servicebus2.caixa.gov.br/portaldeloterias/api/
      - PORT=8080